name: CI

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: |
          cd web
          yarn install --frozen-lockfile

      - name: Run ESLint
        run: |
          cd web
          yarn lint

      - name: Run Prettier
        run: |
          cd web
          yarn format:check

      - name: Run Build
        run: |
          cd web
          yarn build

